# Generated by Django 4.1 on 2022-11-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfoXpath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.CreateModel(
            name="MySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.CreateModel(
            name="SignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.CreateModel(
            name="SingInXpath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.CreateModel(
            name="TorrentListXpath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.CreateModel(
            name="WebSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "url",
                    models.URLField(
                        default="",
                        help_text='请保留网址结尾的"/"',
                        unique=True,
                        verbose_name="站点网址",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="站点名称")),
                (
                    "schemas",
                    models.CharField(
                        choices=[
                            ("AvistaZ", "AvistaZ"),
                            ("Discuz", "Discuz"),
                            ("Gazelle", "Gazelle"),
                            ("IPTorrents", "IPTorrents"),
                            ("meanTorrent", "meanTorrent"),
                            ("NexusPHP", "NexusPHP"),
                        ],
                        default="NexusPHP",
                        max_length=16,
                        verbose_name="站点架构",
                    ),
                ),
                (
                    "logo",
                    models.URLField(
                        default="", help_text="站点logo图标", verbose_name="站点logo"
                    ),
                ),
                (
                    "tracker",
                    models.CharField(
                        default="",
                        help_text="tracker网址关键字",
                        max_length=32,
                        verbose_name="tracker",
                    ),
                ),
                (
                    "page_default",
                    models.JSONField(
                        default={"默认": "torrents.php"},
                        max_length=64,
                        verbose_name="搜索页面",
                    ),
                ),
                (
                    "page_sign_in",
                    models.CharField(
                        default="attendance.php", max_length=64, verbose_name="默认签到链接"
                    ),
                ),
                (
                    "page_control_panel",
                    models.CharField(
                        default="usercp.php", max_length=64, verbose_name="控制面板"
                    ),
                ),
                (
                    "page_detail",
                    models.CharField(
                        default="details.php?id={}",
                        max_length=64,
                        verbose_name="详情页面链接",
                    ),
                ),
                (
                    "page_download",
                    models.CharField(
                        default="download.php?id={}",
                        max_length=64,
                        verbose_name="默认下载链接",
                    ),
                ),
                (
                    "page_user",
                    models.CharField(
                        default="userdetails.php?id={}",
                        max_length=64,
                        verbose_name="用户信息链接",
                    ),
                ),
                (
                    "page_search",
                    models.CharField(
                        default="torrents.php?search={}",
                        max_length=64,
                        verbose_name="搜索链接",
                    ),
                ),
                (
                    "page_leeching",
                    models.CharField(
                        default="getusertorrentlistajax.php?userid={}&type=leeching",
                        max_length=64,
                        verbose_name="当前下载信息",
                    ),
                ),
                (
                    "page_uploaded",
                    models.CharField(
                        default="getusertorrentlistajax.php?userid={}&type=uploaded",
                        max_length=64,
                        verbose_name="发布种子信息",
                    ),
                ),
                (
                    "page_seeding",
                    models.CharField(
                        default="getusertorrentlistajax.php?userid={}&type=seeding",
                        max_length=64,
                        verbose_name="当前做种信息",
                    ),
                ),
                (
                    "page_completed",
                    models.CharField(
                        default="getusertorrentlistajax.php?userid={}&type=completed",
                        max_length=64,
                        verbose_name="完成种子信息",
                    ),
                ),
                (
                    "page_mybonus",
                    models.CharField(
                        default="mybonus.php", max_length=64, verbose_name="魔力值页面"
                    ),
                ),
                (
                    "page_viewfilelist",
                    models.CharField(
                        default="viewfilelist.php?id={}",
                        max_length=64,
                        verbose_name="文件列表链接",
                    ),
                ),
                (
                    "page_viewpeerlist",
                    models.CharField(
                        default="viewpeerlist.php?id={}",
                        max_length=64,
                        verbose_name="当前用户列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "站点信息",
                "verbose_name_plural": "站点信息",
                "ordering": ["name"],
            },
        ),
    ]
