# Generated by Django 4.1 on 2022-11-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.AlterModelOptions(
            name="website",
            options={
                "ordering": ["name"],
                "verbose_name": "PT站点",
                "verbose_name_plural": "PT站点",
            },
        ),
        migrations.RemoveField(model_name="website", name="page_completed", ),
        migrations.RemoveField(model_name="website", name="page_control_panel", ),
        migrations.RemoveField(model_name="website", name="page_default", ),
        migrations.RemoveField(model_name="website", name="page_detail", ),
        migrations.RemoveField(model_name="website", name="page_download", ),
        migrations.RemoveField(model_name="website", name="page_leeching", ),
        migrations.RemoveField(model_name="website", name="page_mybonus", ),
        migrations.RemoveField(model_name="website", name="page_search", ),
        migrations.RemoveField(model_name="website", name="page_seeding", ),
        migrations.RemoveField(model_name="website", name="page_sign_in", ),
        migrations.RemoveField(model_name="website", name="page_uploaded", ),
        migrations.RemoveField(model_name="website", name="page_user", ),
        migrations.RemoveField(model_name="website", name="page_viewfilelist", ),
        migrations.RemoveField(model_name="website", name="page_viewpeerlist", ),
        migrations.AddField(
            model_name="website",
            name="nickname",
            field=models.CharField(
                default="", help_text="昵称，小名", max_length=32, verbose_name="别称"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="name",
            field=models.CharField(
                help_text="站点常用名称", max_length=32, verbose_name="站点名称"
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="schemas",
            field=models.CharField(
                choices=[
                    ("AvistaZ", "AvistaZ"),
                    ("Discuz", "Discuz"),
                    ("Gazelle", "Gazelle"),
                    ("IPTorrents", "IPTorrents"),
                    ("MeanTorrent", "MeanTorrent"),
                    ("NexusPHP", "NexusPHP"),
                    ("NextPT", "NextPT"),
                ],
                default="NexusPHP",
                max_length=16,
                verbose_name="站点架构",
            ),
        ),
    ]
