# Generated by Django 4.1 on 2022-11-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_examine_alter_website_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("sort_id", models.IntegerField(default=99, verbose_name="排序")),
                ("user_id", models.CharField(max_length=16, verbose_name="用户ID")),
                (
                    "passkey",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PassKey"
                    ),
                ),
                ("cookie", models.TextField(verbose_name="COOKIE")),
                (
                    "hr",
                    models.BooleanField(
                        default=False, help_text="是否下载HR种子", verbose_name="开启HR下载"
                    ),
                ),
                (
                    "sign_in",
                    models.BooleanField(
                        default=True, help_text="是否开启签到", verbose_name="开启签到"
                    ),
                ),
                (
                    "search",
                    models.BooleanField(
                        default=True, help_text="是否开启搜索", verbose_name="开启搜索"
                    ),
                ),
            ],
            options={"abstract": False, },
        ),
        migrations.DeleteModel(name="MySite", ),
        migrations.AddField(
            model_name="website",
            name="hr",
            field=models.BooleanField(
                default=False, help_text="站点HR状态", verbose_name="H&R"
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="sign_in",
            field=models.BooleanField(
                default=False, help_text="是否需要签到", verbose_name="签到"
            ),
        ),
        migrations.AddField(
            model_name="ownsite",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="website.website",
                verbose_name="站点",
            ),
        ),
    ]
