# Generated by Django 4.1 on 2022-11-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_signin_options"),
    ]

    operations = [
        migrations.DeleteModel(name="SingInXpath", ),
        migrations.AlterModelOptions(
            name="examine",
            options={
                "ordering": ["site"],
                "verbose_name": "新手考核",
                "verbose_name_plural": "新手考核",
            },
        ),
        migrations.RenameField(
            model_name="website", old_name="examine", new_name="exam",
        ),
        migrations.AddField(
            model_name="examine",
            name="avg_seed_time",
            field=models.FloatField(
                default=0, help_text="计算单位：小时", verbose_name="平均做种时间"
            ),
        ),
        migrations.AddField(
            model_name="examine",
            name="bouns",
            field=models.FloatField(default=0, verbose_name="魔力值"),
        ),
        migrations.AddField(
            model_name="examine",
            name="downloaded",
            field=models.FloatField(
                default=50, help_text="计算单位：GB", verbose_name="魔力值"
            ),
        ),
        migrations.AddField(
            model_name="examine",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="考核结束时间"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examine",
            name="rate",
            field=models.FloatField(default=0, verbose_name="做种率"),
        ),
        migrations.AddField(
            model_name="examine",
            name="score",
            field=models.FloatField(default=0, verbose_name="做种积分"),
        ),
        migrations.AddField(
            model_name="examine",
            name="site",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.website",
                verbose_name="站点",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examine",
            name="uploaded",
            field=models.FloatField(
                default=50, help_text="计算单位：GB", verbose_name="上传量"
            ),
        ),
        migrations.AddField(
            model_name="infoxpath",
            name="site",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.website",
                verbose_name="站点",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="torrentlistxpath",
            name="site",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.website",
                verbose_name="站点",
            ),
            preserve_default=False,
        ),
    ]
