# Generated by Django 4.1 on 2022-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_pt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notify",
            name="name",
            field=models.CharField(
                choices=[
                    ("wechat_work_push", "企业微信通知"),
                    ("wxpusher_push", "WxPusher通知"),
                    ("pushdeer_push", "PushDeer通知"),
                    ("bark_push", "Bark通知"),
                    ("iyuu_push", "爱语飞飞"),
                ],
                default="wechat_work_push",
                max_length=64,
                verbose_name="通知方式",
            ),
        ),
        migrations.AlterField(
            model_name="taskjob",
            name="expression_time",
            field=models.CharField(
                help_text="在间隔任务表示间隔时长使用数字，单位：秒，corn任务中为五位corn表达式：“15 8 * * 2022”",
                max_length=64,
                verbose_name="时间表达式",
            ),
        ),
        migrations.AlterField(
            model_name="taskjob",
            name="jitter",
            field=models.IntegerField(
                default=1200, help_text="增强时间随机性", verbose_name="时间浮动参数"
            ),
        ),
        migrations.AlterField(
            model_name="taskjob",
            name="misfire_grace_time",
            field=models.IntegerField(
                default=600,
                help_text="强制执行结束的时间, 为避免撞车导致任务丢失, 没执行完就别执行了",
                verbose_name="任务运行时间",
            ),
        ),
        migrations.AlterField(
            model_name="taskjob",
            name="task_exec",
            field=models.BooleanField(default=True, verbose_name="开启任务"),
        ),
    ]
