# Generated by Django 4.1.2 on 2022-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_pt', '0003_taskjob_name_alter_taskjob_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskjob',
            name='job_id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='taskjob',
            name='name',
            field=models.CharField(help_text='你对任务的描述，此项具有唯一性', max_length=16, verbose_name='任务名称'),
        ),
    ]
