# Generated by Django 4.1 on 2022-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pt_site", "0015_alter_site_sale_expire_rule_alter_site_title_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="tracker",
            field=models.URLField(
                default="", help_text="tracker网址关键字", verbose_name="tracker"
            ),
        ),
    ]
