# Generated by Django 4.1 on 2022-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pt_site", "0016_site_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="tracker",
            field=models.CharField(
                default="",
                help_text="tracker网址关键字",
                max_length=32,
                verbose_name="tracker",
            ),
        ),
    ]
