# Generated by Django 4.1.2 on 2022-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0017_alter_site_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='user_agent',
            field=models.CharField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42', help_text='请填写你获取cookie的浏览器的User-Agent', max_length=512, verbose_name='User-Agent'),
        ),
    ]
