# Generated by Django 4.1.2 on 2022-11-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0018_mysite_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='sp_hour',
            field=models.FloatField(default=0, verbose_name='时魔'),
        ),
    ]
