# Generated by Django 4.1.2 on 2022-11-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0019_alter_mysite_sp_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='time_join',
            field=models.DateTimeField(blank=True, help_text='请务必填写此项！', null=True, verbose_name='注册时间'),
        ),
    ]
