# Generated by Django 4.1.2 on 2022-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0020_alter_mysite_time_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='cookie',
            field=models.TextField(help_text='与UA搭配使用效果更佳，请和UA在同一浏览器提取', verbose_name='COOKIE'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='user_agent',
            field=models.TextField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42', help_text='请填写你获取cookie的浏览器的User-Agent', verbose_name='User-Agent'),
        ),
    ]
