# Generated by Django 4.1.2 on 2023-01-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0022_alter_mysite_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='nickname',
            field=models.CharField(default='', help_text='英文，用于刷流', max_length=8, verbose_name='简称'),
        ),
        migrations.AddField(
            model_name='site',
            name='page_hr',
            field=models.CharField(default='myhr.php?hrtype=1&userid={}', max_length=64, verbose_name='HR考核页面'),
        ),
        migrations.AddField(
            model_name='site',
            name='search_params',
            field=models.CharField(default='{"免费":"spstate=2","2X":"spstate=3","2X免费":"spstate=4","50%":"spstate=5","2X 50%":"spstate=6",}', help_text='字典格式：{"accept":"application/json","c":"d"}', max_length=128, verbose_name='搜索参数'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='user_id',
            field=models.CharField(help_text='请填写<font color="orangered">数字UID</font>，<font color="orange">* az,cz,ez,莫妮卡、普斯特请填写用户名</font>', max_length=16, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='get_torrent_support',
            field=models.BooleanField(default=True, verbose_name='拉取种子'),
        ),
        migrations.AlterField(
            model_name='site',
            name='get_userinfo_support',
            field=models.BooleanField(default=True, verbose_name='站点数据'),
        ),
        migrations.AlterField(
            model_name='site',
            name='page_default',
            field=models.CharField(default='torrents.php?incldead=1', max_length=64, verbose_name='默认搜索页面'),
        ),
        migrations.AlterField(
            model_name='site',
            name='page_search',
            field=models.CharField(default='torrents.php?incldead=1&search={}', max_length=64, verbose_name='搜索链接'),
        ),
    ]
