# Generated by Django 4.1.2 on 2023-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0023_site_nickname_site_page_hr_site_search_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='full_site_free',
            field=models.CharField(default='//td/b/a/font[contains(text(),"全站") and contains(text(),"Free")]/text()', help_text='获取新公告', max_length=128, verbose_name='站免规则'),
        ),
        migrations.AddField(
            model_name='site',
            name='message_title',
            field=models.CharField(default='//img[@alt="Unread"]/parent::div/following-sibling::a[1]/div/text()', help_text='获取邮件标题', max_length=128, verbose_name='邮件信息'),
        ),
        migrations.AddField(
            model_name='site',
            name='page_message',
            field=models.CharField(default='messages.php', max_length=64, verbose_name='消息页面'),
        ),
    ]
