# Generated by Django 4.1.2 on 2023-01-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0025_userlevelrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlevelrule',
            options={'verbose_name': '升级进度', 'verbose_name_plural': '升级进度'},
        ),
        migrations.AlterField(
            model_name='userlevelrule',
            name='days',
            field=models.IntegerField(default=0, help_text='单位：天', verbose_name='时 间'),
        ),
        migrations.AlterField(
            model_name='userlevelrule',
            name='downloaded',
            field=models.IntegerField(default=0, help_text='单位：GB', verbose_name='下 载'),
        ),
        migrations.AlterField(
            model_name='userlevelrule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pt_site.site', verbose_name='站 点'),
        ),
        migrations.AlterField(
            model_name='userlevelrule',
            name='uploaded',
            field=models.IntegerField(default=0, help_text='单位：GB', verbose_name='上 传'),
        ),
        migrations.AlterUniqueTogether(
            name='userlevelrule',
            unique_together={('site', 'level_id')},
        ),
    ]
