# Generated by Django 4.1.2 on 2023-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0028_userlevelrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevelrule',
            name='downloaded',
            field=models.CharField(default=0, help_text='原样输入，例：50GB，1.5TB', max_length=12, verbose_name='下 载'),
        ),
        migrations.AlterField(
            model_name='userlevelrule',
            name='uploaded',
            field=models.CharField(default=0, help_text='原样输入，例：50GB，1.5TB', max_length=12, verbose_name='上 传'),
        ),
    ]
