# Generated by Django 4.1.2 on 2023-01-08 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0030_alter_userlevelrule_days_alter_userlevelrule_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 10, 44, 723377), help_text='COOKIE有效期', verbose_name='COOKIE有效期'),
        ),
    ]
