# Generated by Django 4.1.2 on 2023-01-08 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0031_mysite_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 41, 28, 814221), help_text='COOKIE有效期', verbose_name='COOKIE有效期'),
        ),
    ]
