# Generated by Django 4.1.2 on 2023-01-16 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0032_alter_mysite_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='notice_content',
            field=models.CharField(default='//td[@class="text"]/div/a/following-sibling::div/font/font', help_text='获取公告内容', max_length=128, verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 17, 43, 42, 327379), help_text='COOKIE有效期', verbose_name='COOKIE有效期'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_site_free',
            field=models.CharField(default='//td/b/a/font[contains(text(),"全站") and contains(text(),"Free")]/text()', help_text='站免信息', max_length=128, verbose_name='站免规则'),
        ),
    ]
