# Generated by Django 4.1.2 on 2023-01-17 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0033_site_notice_content_alter_mysite_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 9, 40, 13, 330488), help_text='COOKIE有效期', verbose_name='COOKIE有效期'),
        ),
        migrations.AlterField(
            model_name='site',
            name='notice_content',
            field=models.CharField(default='//td[@class="text"]/div/a/following-sibling::div', help_text='获取公告内容', max_length=128, verbose_name='公告内容'),
        ),
    ]
