# Generated by Django 4.1.2 on 2023-01-17 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0034_alter_mysite_expires_alter_site_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='page_index',
            field=models.CharField(default='index.php', max_length=64, verbose_name='首页'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 30), help_text='COOKIE有效期', verbose_name='COOKIE有效期'),
        ),
    ]
