# Generated by Django 4.1.2 on 2023-01-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0035_site_page_index_alter_mysite_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlevelrule",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pt_site.site",
                to_field="url",
                verbose_name="站 点",
            ),
        ),
    ]
