# Generated by Django 4.1.2 on 2023-01-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0036_alter_userlevelrule_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="nickname",
            field=models.CharField(
                default="", help_text="英文，用于刷流", max_length=16, verbose_name="简称"
            ),
        ),
    ]
