# Generated by Django 4.1.2 on 2023-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0038_remove_mysite_invitation_remove_mysite_leech_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="publish_rule",
            field=models.CharField(
                default="//p/preceding-sibling::b/text()[1]",
                max_length=128,
                verbose_name="发种数量",
            ),
        ),
    ]
