# Generated by Django 4.1.2 on 2023-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0040_site_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="identity",
            field=models.IntegerField(
                help_text="唯一值，自行适配站点的请填写的尽量大", unique=True, verbose_name="认证ID"
            ),
        ),
    ]
