# Generated by Django 4.1.2 on 2023-01-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0041_alter_site_identity"),
    ]

    operations = [
        migrations.RemoveField(model_name="site", name="download_url_rule",),
        migrations.RemoveField(model_name="site", name="hash_rule",),
        migrations.RemoveField(model_name="site", name="peer_speed_rule",),
        migrations.RemoveField(model_name="site", name="record_count_rule",),
        migrations.RemoveField(model_name="site", name="viewfilelist_rule",),
        migrations.RemoveField(model_name="site", name="viewpeerlist_rule",),
        migrations.AddField(
            model_name="site",
            name="detail_area_rule",
            field=models.CharField(
                default='//h1/following::td/b[contains(text(),"地区")]/text()',
                max_length=128,
                verbose_name="详情页种子地区",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_category_rule",
            field=models.CharField(
                default='//td/b[contains(text(),"类型")]/following-sibling::text()[1]',
                max_length=128,
                verbose_name="详情页种子类型",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_count_files_rule",
            field=models.CharField(
                default='//td/b[contains(text(),"文件数")]/following-sibling::text()[1]',
                max_length=128,
                verbose_name="详情页文件数",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_douban_rule",
            field=models.CharField(
                default='//td/a[starts-with(@href,"https://movie.douban.com/subject/")][1]',
                help_text="提取做种列表中文件大小计算总量",
                max_length=128,
                verbose_name="详情页豆瓣信息",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_download_url_rule",
            field=models.CharField(
                default='//a[@class="index" and contains(@href,"download.php")]/@href',
                max_length=128,
                verbose_name="详情页种子链接",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_free_expire_rule",
            field=models.CharField(
                default='//h1/b/font[contains(@class,"free")]/parent::b/following-sibling::b/span/@title',
                max_length=128,
                verbose_name="详情页促销时间",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_free_rule",
            field=models.CharField(
                default='//td//b[contains(text(),"大小")]/following::text()[1]',
                max_length=128,
                verbose_name="详情页促销标记",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_hash_rule",
            field=models.CharField(
                default='//td/b[contains(text(),"Hash")]/following-sibling::text()[1]',
                max_length=128,
                verbose_name="详情页种子HASH",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_size_rule",
            field=models.CharField(
                default='//td//b[contains(text(),"大小")]/following::text()[1]',
                max_length=128,
                verbose_name="详情页种子大小",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_subtitle_rule",
            field=models.CharField(
                default='//td[contains(text(),"副标题")]/following-sibling::td/text()[1]',
                max_length=128,
                verbose_name="详情页种子副标题",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_title_rule",
            field=models.CharField(
                default="//h1/text()[1]", max_length=128, verbose_name="详情页种子标题"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="detail_year_publish_rule",
            field=models.CharField(
                default='year_current_publish: //td/b[contains(text(),"发行版年份")]/text()',
                help_text="提取做种列表中文件大小计算总量",
                max_length=128,
                verbose_name="详情页豆瓣信息",
            ),
        ),
        migrations.AlterField(
            model_name="userlevelrule",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pt_site.site",
                to_field="identity",
                verbose_name="站 点",
            ),
        ),
    ]
