# Generated by Django 4.1.2 on 2023-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pt_site",
            "0042_remove_site_download_url_rule_remove_site_hash_rule_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userlevelrule",
            name="leeches",
            field=models.IntegerField(default=0, help_text="完成种子数", verbose_name="吸血数"),
        ),
        migrations.AddField(
            model_name="userlevelrule",
            name="seeding_delta",
            field=models.FloatField(default=0, help_text="累计做种时间", verbose_name="做种时间"),
        ),
        migrations.AlterField(
            model_name="userlevelrule",
            name="bonus",
            field=models.FloatField(default=0, verbose_name="魔 力"),
        ),
        migrations.AlterField(
            model_name="userlevelrule",
            name="torrents",
            field=models.IntegerField(default=0, help_text="发布种子数", verbose_name="发 种"),
        ),
    ]
